"""DOCX renderer (python-docx): headings, paragraphs, corporate tables, footer with page numbers."""

from __future__ import annotations

import io

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from docx.shared import Pt, RGBColor

from app.reports.renderers.markdown_util import blocks, strip_inline


def _page_number(paragraph):
    run = paragraph.add_run()
    for tag, text in (("begin", None), (None, "PAGE"), ("end", None)):
        if tag:
            el = OxmlElement("w:fldChar")
            el.set(qn("w:fldCharType"), tag)
        else:
            el = OxmlElement("w:instrText")
            el.set(qn("xml:space"), "preserve")
            el.text = text
        run._r.append(el)


def _table(doc, columns, rows):
    t = doc.add_table(rows=1, cols=len(columns))
    t.style = "Light Grid Accent 1"
    for i, c in enumerate(columns):
        cell = t.rows[0].cells[i]
        cell.text = strip_inline(str(c))
        for p in cell.paragraphs:
            for r in p.runs:
                r.font.bold = True
                r.font.size = Pt(8)
    for row in rows:
        cells = t.add_row().cells
        for i, c in enumerate(row[: len(columns)]):
            cells[i].text = strip_inline(str(c))
            for p in cells[i].paragraphs:
                for r in p.runs:
                    r.font.size = Pt(8)
    doc.add_paragraph()


def render(payload: dict) -> bytes:
    doc = Document()
    style = doc.styles["Normal"]
    style.font.name = "Calibri"
    style.font.size = Pt(10)
    title = doc.add_heading(payload["title"], 0)
    title.alignment = WD_ALIGN_PARAGRAPH.LEFT
    doc.add_paragraph(payload["organization"])
    doc.add_paragraph(f"Reporting period: {payload['period']}")
    doc.add_paragraph(f"Frameworks: {', '.join(payload['frameworks'])}")
    if payload.get("watermark"):
        p = doc.add_paragraph()
        r = p.add_run(payload["watermark"])
        r.font.color.rgb = RGBColor(0xB0, 0x3A, 0x2E)
        r.font.bold = True
    doc.add_paragraph(f"Generated by ESG Nexus on {payload['generated_at']}.")
    doc.add_page_break()
    doc.add_heading("Table of Contents", 1)
    for s in payload["sections"]:
        if s["code"] != "cover":
            doc.add_paragraph(s["title"], style="List Number" if s["level"] <= 1 else "List Bullet")
    doc.add_page_break()
    for s in payload["sections"]:
        if s["code"] == "cover":
            continue
        doc.add_heading(s["title"], 1 if s["level"] <= 1 else 2)
        if s.get("requirement_codes"):
            p = doc.add_paragraph("Disclosures: " + ", ".join(s["requirement_codes"]))
            p.runs[0].font.size = Pt(8)
        for b in blocks(s["content_md"]):
            if b["type"] == "heading":
                doc.add_heading(strip_inline(b["text"]), 3)
            elif b["type"] == "paragraph":
                doc.add_paragraph(strip_inline(b["text"]))
            elif b["type"] == "table":
                _table(doc, b["columns"], b["rows"])
        for t in s.get("tables") or []:
            doc.add_heading(t["title"], 3)
            _table(doc, t["columns"], t["rows"])
        if s.get("evidence_codes"):
            p = doc.add_paragraph("Evidence: " + ", ".join(s["evidence_codes"][:12]))
            p.runs[0].font.size = Pt(8)
    footer = doc.sections[0].footer.paragraphs[0]
    footer.text = f"{payload['organization']} · {payload['title']} · Page "
    _page_number(footer)
    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()
