"""PDF renderer (reportlab): cover, table of contents, numbered sections, corporate tables, page numbers, footer."""

from __future__ import annotations

import io

from reportlab.lib import colors
from reportlab.lib.enums import TA_JUSTIFY
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import KeepTogether, PageBreak, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

from app.reports.renderers.markdown_util import blocks, strip_inline

NAVY = colors.HexColor("#0F2A44")
TEAL = colors.HexColor("#1B7F79")
GREY = colors.HexColor("#5B6470")
LIGHT = colors.HexColor("#F2F5F8")


def _styles():
    ss = getSampleStyleSheet()
    return {
        "title": ParagraphStyle("t", parent=ss["Title"], fontName="Helvetica-Bold", fontSize=26, textColor=NAVY, leading=32, spaceAfter=12),
        "sub": ParagraphStyle("s", parent=ss["Normal"], fontName="Helvetica", fontSize=12, textColor=GREY, leading=16),
        "h1": ParagraphStyle("h1", parent=ss["Heading1"], fontName="Helvetica-Bold", fontSize=16, textColor=NAVY, spaceBefore=14, spaceAfter=8),
        "h2": ParagraphStyle("h2", parent=ss["Heading2"], fontName="Helvetica-Bold", fontSize=13, textColor=TEAL, spaceBefore=10, spaceAfter=6),
        "h3": ParagraphStyle("h3", parent=ss["Heading3"], fontName="Helvetica-Bold", fontSize=11, textColor=NAVY, spaceBefore=8, spaceAfter=4),
        "body": ParagraphStyle("b", parent=ss["Normal"], fontName="Helvetica", fontSize=9.5, leading=13.5, alignment=TA_JUSTIFY, spaceAfter=6),
        "small": ParagraphStyle("sm", parent=ss["Normal"], fontName="Helvetica", fontSize=7.5, leading=9.5, textColor=GREY),
        "cell": ParagraphStyle("c", parent=ss["Normal"], fontName="Helvetica", fontSize=7.5, leading=9.5),
        "cellh": ParagraphStyle("ch", parent=ss["Normal"], fontName="Helvetica-Bold", fontSize=7.5, leading=9.5, textColor=colors.white),
    }


def _table(columns: list[str], rows: list[list], st, *, width: float) -> Table:
    data = [[Paragraph(strip_inline(str(c)), st["cellh"]) for c in columns]] + [[Paragraph(strip_inline(str(c)), st["cell"]) for c in r] for r in rows]
    ncol = max(1, len(columns))
    first = min(width * 0.34, 62 * mm) if ncol > 2 else width / ncol
    other = (width - first) / max(1, ncol - 1) if ncol > 1 else width
    t = Table(data, colWidths=[first] + [other] * (ncol - 1), repeatRows=1)
    t.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), NAVY),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, LIGHT]),
                ("LINEBELOW", (0, 0), (-1, -1), 0.25, colors.HexColor("#C9D2DC")),
                ("LEFTPADDING", (0, 0), (-1, -1), 4),
                ("RIGHTPADDING", (0, 0), (-1, -1), 4),
                ("TOPPADDING", (0, 0), (-1, -1), 3),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
            ]
        )
    )
    return t


def render(payload: dict) -> bytes:
    buf = io.BytesIO()
    st = _styles()
    doc = SimpleDocTemplate(buf, pagesize=A4, leftMargin=18 * mm, rightMargin=18 * mm, topMargin=20 * mm, bottomMargin=18 * mm, title=payload["title"], author="ESG Nexus")
    width = A4[0] - 36 * mm
    story = []
    # cover
    story += [
        Spacer(1, 60 * mm),
        Paragraph(payload["title"], st["title"]),
        Paragraph(payload["organization"], st["sub"]),
        Paragraph(f"Reporting period: {payload['period']}", st["sub"]),
        Paragraph(f"Frameworks: {', '.join(payload['frameworks'])}", st["sub"]),
        Spacer(1, 8 * mm),
    ]
    if payload.get("watermark"):
        story.append(Paragraph(f"<font color='#B03A2E'><b>{payload['watermark']}</b></font>", st["sub"]))
    rd = payload.get("readiness") or {}
    if rd.get("overall") is not None:
        story.append(Paragraph(f"Report readiness at generation: {rd.get('overall')}% · Status: {payload['status']}", st["sub"]))
    story.append(Paragraph(f"Generated by ESG Nexus on {payload['generated_at']}. Every figure is traceable to a governed metric and linked evidence.", st["small"]))
    story.append(PageBreak())
    # table of contents
    story.append(Paragraph("Table of Contents", st["h1"]))
    n1 = 0
    numbered = []
    for s in payload["sections"]:
        if s["code"] == "cover":
            continue
        if s["level"] <= 1:
            n1 += 1
            n2 = 0
            num = f"{n1}"
        else:
            n2 += 1
            num = f"{n1}.{n2}"
        numbered.append((num, s))
        story.append(Paragraph(f"{num}&nbsp;&nbsp;{s['title']}", st["body"] if s["level"] <= 1 else st["small"]))
    story.append(PageBreak())
    # sections
    for num, s in numbered:
        story.append(Paragraph(f"{num} {s['title']}", st["h1"] if s["level"] <= 1 else st["h2"]))
        if s.get("requirement_codes"):
            story.append(Paragraph("Disclosures: " + ", ".join(s["requirement_codes"]), st["small"]))
        for b in blocks(s["content_md"]):
            if b["type"] == "heading":
                story.append(Paragraph(strip_inline(b["text"]), st["h3"]))
            elif b["type"] == "paragraph":
                story.append(Paragraph(strip_inline(b["text"]).replace("&", "&amp;").replace("<", "&lt;"), st["body"]))
            elif b["type"] == "table":
                story.append(_table(b["columns"], b["rows"], st, width=width))
                story.append(Spacer(1, 4))
        for t in s.get("tables") or []:
            story.append(KeepTogether([Paragraph(t["title"], st["h3"]), _table(t["columns"], t["rows"], st, width=width), Spacer(1, 4)]))
        if s.get("evidence_codes"):
            story.append(Paragraph("Evidence: " + ", ".join(s["evidence_codes"][:12]), st["small"]))
        story.append(Spacer(1, 6))

    def _footer(canvas, doc_):
        canvas.saveState()
        canvas.setFont("Helvetica", 7.5)
        canvas.setFillColor(GREY)
        canvas.drawString(18 * mm, 10 * mm, f"{payload['organization']} · {payload['title']}")
        canvas.drawRightString(A4[0] - 18 * mm, 10 * mm, f"Page {doc_.page}")
        if payload.get("watermark"):
            canvas.setFont("Helvetica-Bold", 40)
            canvas.setFillColor(colors.Color(0.7, 0.2, 0.2, alpha=0.08))
            canvas.translate(A4[0] / 2, A4[1] / 2)
            canvas.rotate(35)
            canvas.drawCentredString(0, 0, "DRAFT")
        canvas.restoreState()

    doc.build(story, onFirstPage=_footer, onLaterPages=_footer)
    return buf.getvalue()
