"""initial schema

Revision ID: 5f7f01feec2c
Revises: 
Create Date: 2026-09-04 14:53:35.887169
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '5f7f01feec2c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('code', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('responsibilities', sa.JSON(), nullable=True),
    sa.Column('tools', sa.JSON(), nullable=True),
    sa.Column('expert_profile', sa.String(length=64), nullable=True),
    sa.Column('version', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agents')),
    sa.UniqueConstraint('code', name=op.f('uq_agents_code'))
    )
    op.create_table('esg_topics',
    sa.Column('code', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('pillar', sa.String(length=24), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_esg_topics')),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_topics_tenant_code')
    )
    with op.batch_alter_table('esg_topics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_esg_topics_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('evaluations',
    sa.Column('object_type', sa.String(length=32), nullable=False),
    sa.Column('object_id', sa.String(length=64), nullable=False),
    sa.Column('evaluator', sa.String(length=32), nullable=False),
    sa.Column('dimension', sa.String(length=24), nullable=False),
    sa.Column('scores', sa.JSON(), nullable=False),
    sa.Column('overall', sa.Float(), nullable=False),
    sa.Column('findings', sa.JSON(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluations'))
    )
    with op.batch_alter_table('evaluations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluations_object_id'), ['object_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluations_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('frameworks',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('publisher', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('jurisdiction', sa.String(length=80), nullable=True),
    sa.Column('industry', sa.String(length=120), nullable=True),
    sa.Column('is_custom', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_frameworks')),
    sa.UniqueConstraint('code', name=op.f('uq_frameworks_code'))
    )
    op.create_table('governance_policies',
    sa.Column('code', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner', sa.String(length=120), nullable=True),
    sa.Column('version', sa.String(length=16), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('evidence_code', sa.String(length=64), nullable=True),
    sa.Column('external_ref', sa.String(length=300), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_governance_policies')),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_policies_tenant_code')
    )
    with op.batch_alter_table('governance_policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_governance_policies_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('governance_rules',
    sa.Column('code', sa.String(length=48), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=12), nullable=False),
    sa.Column('scope', sa.String(length=24), nullable=False),
    sa.Column('condition', sa.Text(), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('required_action', sa.Text(), nullable=True),
    sa.Column('owner', sa.String(length=120), nullable=True),
    sa.Column('version', sa.String(length=16), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('approval_status', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('policy_code', sa.String(length=48), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_governance_rules')),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_rules_tenant_code')
    )
    with op.batch_alter_table('governance_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_governance_rules_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('knowledge_documents',
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('version', sa.String(length=24), nullable=False),
    sa.Column('source_ref', sa.String(length=300), nullable=True),
    sa.Column('freshness_date', sa.Date(), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_documents')),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_knowledge_docs_tenant_code')
    )
    with op.batch_alter_table('knowledge_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_documents_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('metric_definitions',
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('pillar', sa.String(length=24), nullable=False),
    sa.Column('topic_code', sa.String(length=48), nullable=False),
    sa.Column('subtopic_code', sa.String(length=48), nullable=True),
    sa.Column('unit', sa.String(length=40), nullable=True),
    sa.Column('frequency', sa.String(length=16), nullable=False),
    sa.Column('data_type', sa.String(length=16), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('calculation_method', sa.Text(), nullable=True),
    sa.Column('formula', sa.Text(), nullable=True),
    sa.Column('required_inputs', sa.JSON(), nullable=True),
    sa.Column('data_sources', sa.JSON(), nullable=True),
    sa.Column('evidence_required', sa.Boolean(), nullable=False),
    sa.Column('evidence_requirements', sa.Text(), nullable=True),
    sa.Column('applicable_frameworks', sa.JSON(), nullable=True),
    sa.Column('materiality_topic', sa.String(length=48), nullable=True),
    sa.Column('assurance_status', sa.String(length=16), nullable=False),
    sa.Column('validation_rules', sa.JSON(), nullable=True),
    sa.Column('aggregation', sa.String(length=16), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('is_kpi', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('owner', sa.String(length=120), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metric_definitions')),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_metric_definitions_tenant_code')
    )
    with op.batch_alter_table('metric_definitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_metric_definitions_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_metric_definitions_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_metric_definitions_topic_code'), ['topic_code'], unique=False)

    op.create_table('organizations',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=True),
    sa.Column('legal_form', sa.String(length=120), nullable=True),
    sa.Column('headquarters', sa.String(length=200), nullable=True),
    sa.Column('country', sa.String(length=80), nullable=True),
    sa.Column('stock_ticker', sa.String(length=40), nullable=True),
    sa.Column('sector', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reporting_boundary', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=200), nullable=True),
    sa.Column('contact', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations')),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_organizations_tenant_code')
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizations_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('report_templates',
    sa.Column('code', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sections', sa.JSON(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_templates')),
    sa.UniqueConstraint('code', name=op.f('uq_report_templates_code'))
    )
    op.create_table('roles',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=400), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('name', name=op.f('uq_roles_name'))
    )
    op.create_table('tenants',
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('deployment_model', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenants')),
    sa.UniqueConstraint('slug', name=op.f('uq_tenants_slug'))
    )
    op.create_table('data_sources',
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner', sa.String(length=120), nullable=True),
    sa.Column('system_name', sa.String(length=120), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_data_sources_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_sources')),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_data_sources_tenant_code')
    )
    with op.batch_alter_table('data_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_sources_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('entities',
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('ownership_pct', sa.Float(), nullable=True),
    sa.Column('consolidation_method', sa.String(length=24), nullable=False),
    sa.Column('in_reporting_boundary', sa.Boolean(), nullable=False),
    sa.Column('country', sa.String(length=80), nullable=True),
    sa.Column('region', sa.String(length=120), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('sector', sa.String(length=160), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_entities_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['entities.id'], name=op.f('fk_entities_parent_id_entities')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entities')),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_entities_tenant_code')
    )
    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entities_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_entities_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_entities_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('esg_subtopics',
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['esg_topics.id'], name=op.f('fk_esg_subtopics_topic_id_esg_topics'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_esg_subtopics')),
    sa.UniqueConstraint('topic_id', 'code', name='uq_subtopics_topic_code')
    )
    op.create_table('framework_versions',
    sa.Column('framework_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('source_url', sa.String(length=300), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['framework_id'], ['frameworks.id'], name=op.f('fk_framework_versions_framework_id_frameworks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_framework_versions')),
    sa.UniqueConstraint('framework_id', 'version', name='uq_framework_versions_fw_version')
    )
    op.create_table('knowledge_chunks',
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], name=op.f('fk_knowledge_chunks_document_id_knowledge_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_chunks'))
    )
    with op.batch_alter_table('knowledge_chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_chunks_document_id'), ['document_id'], unique=False)

    op.create_table('reporting_periods',
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=24), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('granularity', sa.String(length=12), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('is_baseline', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_reporting_periods_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reporting_periods')),
    sa.UniqueConstraint('tenant_id', 'organization_id', 'code', name='uq_periods_org_code')
    )
    with op.batch_alter_table('reporting_periods', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reporting_periods_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reporting_periods_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('users',
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=300), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_users_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('tenant_id', 'email', name='uq_users_tenant_email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('agent_runs',
    sa.Column('agent_code', sa.String(length=48), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('task', sa.String(length=120), nullable=False),
    sa.Column('input', sa.JSON(), nullable=True),
    sa.Column('output', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('sources', sa.JSON(), nullable=True),
    sa.Column('tools_used', sa.JSON(), nullable=True),
    sa.Column('guardrail_result', sa.JSON(), nullable=True),
    sa.Column('evaluation_id', sa.Integer(), nullable=True),
    sa.Column('expert', sa.String(length=64), nullable=True),
    sa.Column('provider', sa.String(length=24), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], name=op.f('fk_agent_runs_evaluation_id_evaluations')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_agent_runs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_runs'))
    )
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_runs_agent_code'), ['agent_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('approvals',
    sa.Column('object_type', sa.String(length=32), nullable=False),
    sa.Column('object_id', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=24), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('decided_by', sa.Integer(), nullable=True),
    sa.Column('decision', sa.String(length=16), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], name=op.f('fk_approvals_assigned_to_users')),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], name=op.f('fk_approvals_decided_by_users')),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], name=op.f('fk_approvals_requested_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approvals'))
    )
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approvals_object_id'), ['object_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approvals_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('object_type', sa.String(length=48), nullable=False),
    sa.Column('object_id', sa.String(length=64), nullable=True),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_object_id'), ['object_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_object_type'), ['object_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('calculation_runs',
    sa.Column('metric_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('calculation_version', sa.String(length=16), nullable=False),
    sa.Column('formula', sa.Text(), nullable=False),
    sa.Column('inputs', sa.JSON(), nullable=False),
    sa.Column('result', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('executed_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], name=op.f('fk_calculation_runs_entity_id_entities')),
    sa.ForeignKeyConstraint(['executed_by'], ['users.id'], name=op.f('fk_calculation_runs_executed_by_users')),
    sa.ForeignKeyConstraint(['metric_id'], ['metric_definitions.id'], name=op.f('fk_calculation_runs_metric_id_metric_definitions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['period_id'], ['reporting_periods.id'], name=op.f('fk_calculation_runs_period_id_reporting_periods')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calculation_runs'))
    )
    with op.batch_alter_table('calculation_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calculation_runs_metric_id'), ['metric_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_calculation_runs_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('calculation_versions',
    sa.Column('metric_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=16), nullable=False),
    sa.Column('formula', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('methodology_ref', sa.String(length=200), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_calculation_versions_approved_by_users')),
    sa.ForeignKeyConstraint(['metric_id'], ['metric_definitions.id'], name=op.f('fk_calculation_versions_metric_id_metric_definitions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calculation_versions')),
    sa.UniqueConstraint('metric_id', 'version', name='uq_calc_versions_metric_version')
    )
    with op.batch_alter_table('calculation_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calculation_versions_metric_id'), ['metric_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_calculation_versions_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('datasets',
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('period_id', sa.Integer(), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('pillar', sa.String(length=24), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], name=op.f('fk_datasets_entity_id_entities')),
    sa.ForeignKeyConstraint(['period_id'], ['reporting_periods.id'], name=op.f('fk_datasets_period_id_reporting_periods')),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], name=op.f('fk_datasets_source_id_data_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_datasets'))
    )
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_datasets_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_datasets_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_datasets_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('evidence',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('document_ref', sa.String(length=255), nullable=True),
    sa.Column('page_from', sa.Integer(), nullable=True),
    sa.Column('page_to', sa.Integer(), nullable=True),
    sa.Column('printed_page', sa.String(length=24), nullable=True),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('evidence_date', sa.Date(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('period_id', sa.Integer(), nullable=True),
    sa.Column('verification_status', sa.String(length=16), nullable=False),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('file_hash', sa.String(length=80), nullable=True),
    sa.Column('storage_key', sa.String(length=300), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], name=op.f('fk_evidence_entity_id_entities')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_evidence_owner_id_users')),
    sa.ForeignKeyConstraint(['period_id'], ['reporting_periods.id'], name=op.f('fk_evidence_period_id_reporting_periods')),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], name=op.f('fk_evidence_verified_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence')),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_evidence_tenant_code')
    )
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('issues',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=12), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metric_code', sa.String(length=80), nullable=True),
    sa.Column('entity_code', sa.String(length=40), nullable=True),
    sa.Column('period_code', sa.String(length=24), nullable=True),
    sa.Column('requirement_code', sa.String(length=64), nullable=True),
    sa.Column('rule_code', sa.String(length=48), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('required_action', sa.Text(), nullable=True),
    sa.Column('blocks_report', sa.Boolean(), nullable=False),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fingerprint', sa.String(length=120), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], name=op.f('fk_issues_resolved_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_issues'))
    )
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_issues_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_issues_fingerprint'), ['fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_issues_metric_code'), ['metric_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_issues_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('materiality_assessments',
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('methodology', sa.Text(), nullable=True),
    sa.Column('approach', sa.String(length=16), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('evidence_codes', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_materiality_assessments_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['period_id'], ['reporting_periods.id'], name=op.f('fk_materiality_assessments_period_id_reporting_periods')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_materiality_assessments'))
    )
    with op.batch_alter_table('materiality_assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_materiality_assessments_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('notifications',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('link', sa.String(length=300), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('organization_frameworks',
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('framework_version_id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('applicable_scope', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['framework_version_id'], ['framework_versions.id'], name=op.f('fk_organization_frameworks_framework_version_id_framework_versions')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_organization_frameworks_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['period_id'], ['reporting_periods.id'], name=op.f('fk_organization_frameworks_period_id_reporting_periods')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organization_frameworks')),
    sa.UniqueConstraint('organization_id', 'framework_version_id', 'period_id', name='uq_org_frameworks')
    )
    with op.batch_alter_table('organization_frameworks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organization_frameworks_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('quality_scores',
    sa.Column('metric_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('completeness', sa.Float(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('consistency', sa.Float(), nullable=False),
    sa.Column('timeliness', sa.Float(), nullable=False),
    sa.Column('validity', sa.Float(), nullable=False),
    sa.Column('uniqueness', sa.Float(), nullable=False),
    sa.Column('traceability', sa.Float(), nullable=False),
    sa.Column('overall', sa.Float(), nullable=False),
    sa.Column('explanation', sa.JSON(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], name=op.f('fk_quality_scores_entity_id_entities')),
    sa.ForeignKeyConstraint(['metric_id'], ['metric_definitions.id'], name=op.f('fk_quality_scores_metric_id_metric_definitions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['period_id'], ['reporting_periods.id'], name=op.f('fk_quality_scores_period_id_reporting_periods')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quality_scores')),
    sa.UniqueConstraint('metric_id', 'entity_id', 'period_id', name='uq_quality_scores_metric_entity_period')
    )
    with op.batch_alter_table('quality_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quality_scores_metric_id'), ['metric_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quality_scores_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('reports',
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('template_code', sa.String(length=48), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('framework_codes', sa.JSON(), nullable=False),
    sa.Column('scope', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('readiness', sa.JSON(), nullable=True),
    sa.Column('validation_result', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_reports_approved_by_users')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_reports_created_by_users')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_reports_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['period_id'], ['reporting_periods.id'], name=op.f('fk_reports_period_id_reporting_periods')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('requirements',
    sa.Column('framework_version_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('pillar', sa.String(length=24), nullable=True),
    sa.Column('theme', sa.String(length=120), nullable=True),
    sa.Column('disclosure_type', sa.String(length=16), nullable=False),
    sa.Column('evidence_required', sa.Boolean(), nullable=False),
    sa.Column('is_core', sa.Boolean(), nullable=False),
    sa.Column('applicability', sa.JSON(), nullable=True),
    sa.Column('metric_codes', sa.JSON(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('guidance', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['framework_version_id'], ['framework_versions.id'], name=op.f('fk_requirements_framework_version_id_framework_versions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['requirements.id'], name=op.f('fk_requirements_parent_id_requirements')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_requirements')),
    sa.UniqueConstraint('framework_version_id', 'code', name='uq_requirements_fwv_code')
    )
    with op.batch_alter_table('requirements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_requirements_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_requirements_framework_version_id'), ['framework_version_id'], unique=False)

    op.create_table('targets',
    sa.Column('metric_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('baseline_period_id', sa.Integer(), nullable=True),
    sa.Column('target_period_id', sa.Integer(), nullable=True),
    sa.Column('target_year', sa.Integer(), nullable=True),
    sa.Column('baseline_value', sa.Float(), nullable=True),
    sa.Column('target_value', sa.Float(), nullable=True),
    sa.Column('direction', sa.String(length=12), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('source_evidence_code', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['baseline_period_id'], ['reporting_periods.id'], name=op.f('fk_targets_baseline_period_id_reporting_periods')),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], name=op.f('fk_targets_entity_id_entities')),
    sa.ForeignKeyConstraint(['metric_id'], ['metric_definitions.id'], name=op.f('fk_targets_metric_id_metric_definitions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_period_id'], ['reporting_periods.id'], name=op.f('fk_targets_target_period_id_reporting_periods')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_targets'))
    )
    with op.batch_alter_table('targets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_targets_metric_id'), ['metric_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_targets_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], name=op.f('fk_user_roles_entity_id_entities')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_user_roles_organization_id_organizations')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_roles'))
    )
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_roles_user_id'), ['user_id'], unique=False)

    op.create_table('dataset_versions',
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_hash', sa.String(length=80), nullable=True),
    sa.Column('storage_key', sa.String(length=300), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('validation_result', sa.JSON(), nullable=True),
    sa.Column('transformation_history', sa.JSON(), nullable=True),
    sa.Column('quality', sa.JSON(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=120), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_dataset_versions_dataset_id_datasets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_dataset_versions_uploaded_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dataset_versions')),
    sa.UniqueConstraint('dataset_id', 'version', name='uq_dataset_versions_dataset_version')
    )
    with op.batch_alter_table('dataset_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dataset_versions_dataset_id'), ['dataset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dataset_versions_idempotency_key'), ['idempotency_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_dataset_versions_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('framework_mappings',
    sa.Column('requirement_id', sa.Integer(), nullable=False),
    sa.Column('metric_id', sa.Integer(), nullable=True),
    sa.Column('mapping_type', sa.String(length=16), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('omission_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_framework_mappings_created_by_users')),
    sa.ForeignKeyConstraint(['metric_id'], ['metric_definitions.id'], name=op.f('fk_framework_mappings_metric_id_metric_definitions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], name=op.f('fk_framework_mappings_requirement_id_requirements'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_framework_mappings'))
    )
    with op.batch_alter_table('framework_mappings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_framework_mappings_metric_id'), ['metric_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_framework_mappings_requirement_id'), ['requirement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_framework_mappings_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('materiality_topics',
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('topic_code', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('pillar', sa.String(length=24), nullable=False),
    sa.Column('impact_severity', sa.Float(), nullable=True),
    sa.Column('impact_likelihood', sa.Float(), nullable=True),
    sa.Column('impact_score', sa.Float(), nullable=True),
    sa.Column('financial_magnitude', sa.Float(), nullable=True),
    sa.Column('financial_likelihood', sa.Float(), nullable=True),
    sa.Column('financial_score', sa.Float(), nullable=True),
    sa.Column('stakeholder_priority', sa.Float(), nullable=True),
    sa.Column('is_material', sa.Boolean(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('related_metric_codes', sa.JSON(), nullable=True),
    sa.Column('related_requirement_codes', sa.JSON(), nullable=True),
    sa.Column('risks', sa.JSON(), nullable=True),
    sa.Column('opportunities', sa.JSON(), nullable=True),
    sa.Column('evidence_codes', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['materiality_assessments.id'], name=op.f('fk_materiality_topics_assessment_id_materiality_assessments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_materiality_topics'))
    )
    with op.batch_alter_table('materiality_topics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_materiality_topics_assessment_id'), ['assessment_id'], unique=False)

    op.create_table('model_runs',
    sa.Column('agent_run_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=24), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('purpose', sa.String(length=80), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_read_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], name=op.f('fk_model_runs_agent_run_id_agent_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_runs'))
    )
    with op.batch_alter_table('model_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_runs_agent_run_id'), ['agent_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_runs_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('report_sections',
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=48), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('content_md', sa.Text(), nullable=True),
    sa.Column('narrative_source', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('metric_codes', sa.JSON(), nullable=True),
    sa.Column('evidence_codes', sa.JSON(), nullable=True),
    sa.Column('requirement_codes', sa.JSON(), nullable=True),
    sa.Column('tables', sa.JSON(), nullable=True),
    sa.Column('charts', sa.JSON(), nullable=True),
    sa.Column('evaluation_id', sa.Integer(), nullable=True),
    sa.Column('agent_run_id', sa.Integer(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('comments', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], name=op.f('fk_report_sections_agent_run_id_agent_runs')),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_report_sections_approved_by_users')),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], name=op.f('fk_report_sections_evaluation_id_evaluations')),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], name=op.f('fk_report_sections_report_id_reports'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_sections')),
    sa.UniqueConstraint('report_id', 'code', name='uq_report_sections_report_code')
    )
    with op.batch_alter_table('report_sections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_sections_report_id'), ['report_id'], unique=False)

    op.create_table('report_versions',
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('format', sa.String(length=8), nullable=False),
    sa.Column('storage_key', sa.String(length=300), nullable=False),
    sa.Column('file_hash', sa.String(length=80), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('generated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_final', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], name=op.f('fk_report_versions_generated_by_users')),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], name=op.f('fk_report_versions_report_id_reports'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_versions'))
    )
    with op.batch_alter_table('report_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_versions_report_id'), ['report_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_versions_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('stakeholder_inputs',
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('stakeholder_group', sa.String(length=120), nullable=False),
    sa.Column('topic_code', sa.String(length=48), nullable=True),
    sa.Column('priority', sa.Float(), nullable=True),
    sa.Column('channel', sa.String(length=200), nullable=True),
    sa.Column('concern', sa.Text(), nullable=True),
    sa.Column('engagement_value', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['materiality_assessments.id'], name=op.f('fk_stakeholder_inputs_assessment_id_materiality_assessments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stakeholder_inputs'))
    )
    with op.batch_alter_table('stakeholder_inputs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stakeholder_inputs_assessment_id'), ['assessment_id'], unique=False)

    op.create_table('dataset_records',
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('metric_code', sa.String(length=80), nullable=True),
    sa.Column('entity_code', sa.String(length=40), nullable=True),
    sa.Column('period_code', sa.String(length=24), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(length=40), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('issues', sa.JSON(), nullable=True),
    sa.Column('mapping_confidence', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['dataset_versions.id'], name=op.f('fk_dataset_records_version_id_dataset_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dataset_records'))
    )
    with op.batch_alter_table('dataset_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dataset_records_metric_code'), ['metric_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_dataset_records_version_id'), ['version_id'], unique=False)

    op.create_table('metric_values',
    sa.Column('metric_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('value_numeric', sa.Float(), nullable=True),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('source_type', sa.String(length=16), nullable=False),
    sa.Column('dataset_version_id', sa.Integer(), nullable=True),
    sa.Column('calculation_run_id', sa.Integer(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('is_estimate', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_metric_values_approved_by_users')),
    sa.ForeignKeyConstraint(['calculation_run_id'], ['calculation_runs.id'], name=op.f('fk_metric_values_calculation_run_id_calculation_runs')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_metric_values_created_by_users')),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['dataset_versions.id'], name=op.f('fk_metric_values_dataset_version_id_dataset_versions')),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], name=op.f('fk_metric_values_entity_id_entities')),
    sa.ForeignKeyConstraint(['metric_id'], ['metric_definitions.id'], name=op.f('fk_metric_values_metric_id_metric_definitions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['period_id'], ['reporting_periods.id'], name=op.f('fk_metric_values_period_id_reporting_periods')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metric_values')),
    sa.UniqueConstraint('metric_id', 'entity_id', 'period_id', name='uq_metric_values_metric_entity_period')
    )
    with op.batch_alter_table('metric_values', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_metric_values_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_metric_values_metric_id'), ['metric_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_metric_values_period_id'), ['period_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_metric_values_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('evidence_links',
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('metric_id', sa.Integer(), nullable=True),
    sa.Column('metric_value_id', sa.Integer(), nullable=True),
    sa.Column('requirement_id', sa.Integer(), nullable=True),
    sa.Column('report_section_id', sa.Integer(), nullable=True),
    sa.Column('relation', sa.String(length=16), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], name=op.f('fk_evidence_links_evidence_id_evidence'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['metric_id'], ['metric_definitions.id'], name=op.f('fk_evidence_links_metric_id_metric_definitions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['metric_value_id'], ['metric_values.id'], name=op.f('fk_evidence_links_metric_value_id_metric_values'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_section_id'], ['report_sections.id'], name=op.f('fk_evidence_links_report_section_id_report_sections'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], name=op.f('fk_evidence_links_requirement_id_requirements'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_links'))
    )
    with op.batch_alter_table('evidence_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_links_evidence_id'), ['evidence_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_links_metric_id'), ['metric_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_links_metric_value_id'), ['metric_value_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_links_requirement_id'), ['requirement_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evidence_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_links_requirement_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_links_metric_value_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_links_metric_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_links_evidence_id'))

    op.drop_table('evidence_links')
    with op.batch_alter_table('metric_values', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_metric_values_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_metric_values_period_id'))
        batch_op.drop_index(batch_op.f('ix_metric_values_metric_id'))
        batch_op.drop_index(batch_op.f('ix_metric_values_entity_id'))

    op.drop_table('metric_values')
    with op.batch_alter_table('dataset_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dataset_records_version_id'))
        batch_op.drop_index(batch_op.f('ix_dataset_records_metric_code'))

    op.drop_table('dataset_records')
    with op.batch_alter_table('stakeholder_inputs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stakeholder_inputs_assessment_id'))

    op.drop_table('stakeholder_inputs')
    with op.batch_alter_table('report_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_versions_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_report_versions_report_id'))

    op.drop_table('report_versions')
    with op.batch_alter_table('report_sections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_sections_report_id'))

    op.drop_table('report_sections')
    with op.batch_alter_table('model_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_runs_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_model_runs_agent_run_id'))

    op.drop_table('model_runs')
    with op.batch_alter_table('materiality_topics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_materiality_topics_assessment_id'))

    op.drop_table('materiality_topics')
    with op.batch_alter_table('framework_mappings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_framework_mappings_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_framework_mappings_requirement_id'))
        batch_op.drop_index(batch_op.f('ix_framework_mappings_metric_id'))

    op.drop_table('framework_mappings')
    with op.batch_alter_table('dataset_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dataset_versions_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_dataset_versions_idempotency_key'))
        batch_op.drop_index(batch_op.f('ix_dataset_versions_dataset_id'))

    op.drop_table('dataset_versions')
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_roles_user_id'))

    op.drop_table('user_roles')
    with op.batch_alter_table('targets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_targets_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_targets_metric_id'))

    op.drop_table('targets')
    with op.batch_alter_table('requirements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_requirements_framework_version_id'))
        batch_op.drop_index(batch_op.f('ix_requirements_code'))

    op.drop_table('requirements')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_tenant_id'))

    op.drop_table('reports')
    with op.batch_alter_table('quality_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quality_scores_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_quality_scores_metric_id'))

    op.drop_table('quality_scores')
    with op.batch_alter_table('organization_frameworks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organization_frameworks_tenant_id'))

    op.drop_table('organization_frameworks')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_tenant_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('materiality_assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_materiality_assessments_tenant_id'))

    op.drop_table('materiality_assessments')
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_issues_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_issues_metric_code'))
        batch_op.drop_index(batch_op.f('ix_issues_fingerprint'))
        batch_op.drop_index(batch_op.f('ix_issues_code'))

    op.drop_table('issues')
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_code'))

    op.drop_table('evidence')
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_datasets_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_datasets_source_id'))
        batch_op.drop_index(batch_op.f('ix_datasets_code'))

    op.drop_table('datasets')
    with op.batch_alter_table('calculation_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calculation_versions_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_calculation_versions_metric_id'))

    op.drop_table('calculation_versions')
    with op.batch_alter_table('calculation_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calculation_runs_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_calculation_runs_metric_id'))

    op.drop_table('calculation_runs')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_object_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_object_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approvals_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_approvals_object_id'))

    op.drop_table('approvals')
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_runs_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_agent_code'))

    op.drop_table('agent_runs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('reporting_periods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reporting_periods_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_reporting_periods_organization_id'))

    op.drop_table('reporting_periods')
    with op.batch_alter_table('knowledge_chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_chunks_document_id'))

    op.drop_table('knowledge_chunks')
    op.drop_table('framework_versions')
    op.drop_table('esg_subtopics')
    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entities_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_entities_parent_id'))
        batch_op.drop_index(batch_op.f('ix_entities_organization_id'))

    op.drop_table('entities')
    with op.batch_alter_table('data_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_sources_tenant_id'))

    op.drop_table('data_sources')
    op.drop_table('tenants')
    op.drop_table('roles')
    op.drop_table('report_templates')
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_tenant_id'))

    op.drop_table('organizations')
    with op.batch_alter_table('metric_definitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_metric_definitions_topic_code'))
        batch_op.drop_index(batch_op.f('ix_metric_definitions_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_metric_definitions_code'))

    op.drop_table('metric_definitions')
    with op.batch_alter_table('knowledge_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_documents_tenant_id'))

    op.drop_table('knowledge_documents')
    with op.batch_alter_table('governance_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_governance_rules_tenant_id'))

    op.drop_table('governance_rules')
    with op.batch_alter_table('governance_policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_governance_policies_tenant_id'))

    op.drop_table('governance_policies')
    op.drop_table('frameworks')
    with op.batch_alter_table('evaluations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluations_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_evaluations_object_id'))

    op.drop_table('evaluations')
    with op.batch_alter_table('esg_topics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_esg_topics_tenant_id'))

    op.drop_table('esg_topics')
    op.drop_table('agents')
    # ### end Alembic commands ###
